"use server";
import { createClient } from "@/lib/supabase/server";
import type { Habit } from "./types";
import { calculateHabitStreak } from "./streak";
import { completionRate } from "./rates";
const message="\ud1b5\uacc4\ub97c \ubd88\ub7ec\uc624\uc9c0 \ubabb\ud588\uc2b5\ub2c8\ub2e4.";
const validDate=(v:string)=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(v))return false;const [y,m,d]=v.split("-").map(Number),x=new Date(Date.UTC(y,m-1,d));return x.getUTCFullYear()===y&&x.getUTCMonth()===m-1&&x.getUTCDate()===d;};
const zoneDate=(z:string)=>{try{return new Intl.DateTimeFormat("en-CA",{timeZone:z,year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date);}catch{return null;}};const add=(v:string,n:number)=>{const d=new Date(`${v}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);};const dow=(v:string)=>new Date(`${v}T00:00:00Z`).getUTCDay();
function schedule(h:Habit){if(h.schedule_type==="daily")return "\ub9e4\uc77c";if(h.schedule_type==="weekly_target")return `\uc8fc ${h.target_per_week}\ud68c`;const names=["\uc77c","\uc6d4","\ud654","\uc218","\ubaa9","\uae08","\ud1a0"];return (h.days_of_week??[]).sort((a,b)=>a-b).map(d=>names[d]).join(" \u00b7 ");}
export async function getStats(today:string,timezone:string){if(!validDate(today)||!timezone.trim()||timezone.length>100||zoneDate(timezone)!==today)return {success:false as const,message};try{const supabase=await createClient();const {data:auth,error:authError}=await supabase.auth.getClaims();const userId=auth?.claims?.sub;if(authError||!userId)return {success:false as const,message};const {data:habits,error}=await supabase.from("habits").select("id,user_id,name,schedule_type,days_of_week,target_per_week,start_date,archived_at,created_at,updated_at").eq("user_id",userId).is("archived_at",null).lte("start_date",today).returns<Habit[]>();if(error||!habits)return {success:false as const,message};const periodStart=add(today,-29),historyStart=habits.reduce((min,h)=>h.start_date<min?h.start_date:min,today),ids=habits.map(h=>h.id);const result=ids.length?await supabase.from("habit_completions").select("habit_id,completed_date").eq("user_id",userId).in("habit_id",ids).gte("completed_date",historyStart).lte("completed_date",today):{data:[] as {habit_id:string;completed_date:string}[],error:null};if(result.error||!result.data)return {success:false as const,message};const rows=result.data,todaySet=new Set(rows.filter(r=>r.completed_date===today).map(r=>r.habit_id)),recent7=add(today,-6),activity=Array.from({length:7},(_,i)=>{const date=add(recent7,i);return {date,count:rows.filter(r=>r.completed_date===date).length};}),cards=habits.map(h=>{const rate7=completionRate(h,rows,recent7,today),rate30=completionRate(h,rows,periodStart,today);return {id:h.id,name:h.name,schedule:schedule(h),scheduleType:h.schedule_type,targetPerWeek:h.target_per_week,streakCount:calculateHabitStreak(h,rows,today),rate7:rate7.rate,rate30:rate30.rate,rate30Denominator:rate30.denominator,completedToday:todaySet.has(h.id)}}),rates=cards.filter(c=>c.rate30Denominator>0).map(c=>c.rate30);return {success:true as const,activeCount:habits.length,completedToday:cards.filter(c=>c.completedToday).length,averageRate:rates.length?rates.reduce((a,b)=>a+b,0)/rates.length:0,last30Count:rows.filter(r=>r.completed_date>=periodStart).length,activity,cards};}catch(error){console.error("Unexpected error while loading stats",error instanceof Error?error.name:"UnknownError");return {success:false as const,message};}}
